// Copyright (C) 2026 Marcel W. Wysocki
// SPDX-License-Identifier: AGPL-3.0-or-later

package runner

import (
	"context"
	"path"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"

	"golang.org/x/text/unicode/norm"

	"github.com/maci0/gauntlet/internal/fuzzy"
	"github.com/maci0/gauntlet/internal/gitx"
	"github.com/maci0/gauntlet/internal/normalize"
)

// subjectMax is the conventional 72-character cap for a subject, applied to
// the generated and the agent-supplied alike. An agent's SUBJECT: line is
// bounded separately at 100 runes by agent.ParseSubject and already went
// through that sanitizer; the clip here is the second half, the one that keeps
// that 100-rune line from reaching history, a PR title, and a merge message.
const subjectMax = 72

// commitSubject is what the history will say about a review's change: what
// the agent called it, or a summary of the files it actually touched. Neither
// mentions this tool, a review, a run id, or a model: the commit is the
// project's, not the machinery's.
//
// The agent's line is model output, and a prompt asking for a subject is an
// instruction an agent can fail to follow, so nothing about it is taken on
// trust: a subject carrying attribution is dropped for the generated one, and
// the rest is held to the same 72 runes as a generated subject, because it
// becomes a PR title and a merge message as well as a history line.
func commitSubject(fromAgent string, ch gitx.Changes) string {
	if s := strings.TrimSpace(fromAgent); s != "" && !attributesTheModel(s) {
		return clipSubject(s)
	}
	return subjectFromChanges(ch)
}

// attributionRe matches the ways model output credits itself in a commit
// message: an attribution trailer a CLI injects despite the prompt ban, a
// "generated with <tool>" phrase, and the robot emoji. Deliberately narrow: a
// reviewed repository may legitimately change code that talks to any of these
// tools, and a subject naming one ("fix the gemini token cap") is a true
// description of the change. What is rejected is the credit line, not the
// word.
var attributionRe = regexp.MustCompile(`(?i)(?:^|[\s(])(?:co-authored-by|generated-by|made-with)\s*:` +
	`|(?:^|[\s(])(?:generated with|generated by|written by|created by|powered by|reviewed by)\b` +
	`|cursoragent|🤖|\bwith (?:claude|chatgpt|codex|gemini|copilot|cursor|qwen|deepseek|kimi|openai|anthropic)\b`)

// attributesTheModel reports whether a subject credits a model or an agent
// CLI. gitx strips these from a message's trailers once the commit exists; the
// subject is written by the agent's own hand and would carry one straight
// through that sweep, into a permanent history line and a pull request title.
func attributesTheModel(s string) bool {
	return attributionRe.MatchString(s)
}

func treeChanges(ctx context.Context, dir string) gitx.Changes {
	ch, err := gitx.Open(dir).Status(ctx, nil)
	if err != nil {
		return gitx.Changes{}
	}
	return ch
}

func subjectFromChanges(ch gitx.Changes) string {
	files := slices.Concat(ch.Tracked, ch.Untracked)
	if len(files) == 0 {
		return "chore: update files"
	}
	// The order decides which file the subject names, so it is the order a
	// reader would read the list in, not the order the bytes come out in.
	// Sorting by byte value names "Zebra.go" ahead of "apple.go" and every
	// capitalized path ahead of every lowercase one, and that name is what
	// reaches the history, the PR title, and the merge message. fuzzy.Sort is
	// the one ordering in this tree (see its doc for why).
	fuzzy.Sort(files)
	typ := subjectType(files)
	what := subjectWhat(files, len(ch.Tracked) == 0)
	if scope := subjectScope(files); scope != "" {
		return clipSubject(typ + "(" + scope + "): " + what)
	}
	return clipSubject(typ + ": " + what)
}

func subjectType(files []string) string {
	docs, tests, ci := 0, 0, 0
	for _, f := range files {
		// Classification reads the folded path. The tables it consults are
		// lowercase by convention, and the rest of this tree folds a path
		// before looking it up (internal/evidence/suggest.go records a lowercased
		// path and a lowercased extension). A tree holding "FOO_TEST.GO" or a
		// "Docs/" directory would otherwise be typed chore, and on a
		// case-insensitive volume (macOS by default) that is the same
		// directory git and the reviewer are looking at. Only the classification
		// folds: the name printed in the subject is the real spelling.
		slash := strings.ToLower(filepath.ToSlash(f))
		base := path.Base(slash)
		switch {
		case isTestPath(slash, base):
			tests++
		case isDocPath(slash, base):
			docs++
		case isCIPath(slash):
			ci++
		}
	}
	n := len(files)
	switch {
	case tests == n:
		return "test"
	case docs == n:
		return "docs"
	case ci == n:
		return "ci"
	default:
		return "chore"
	}
}

func isTestPath(slash, base string) bool {
	if strings.Contains(slash, "/testdata/") || strings.HasPrefix(slash, "testdata/") {
		return true
	}
	for _, suf := range []string{"_test.go", "_test.py", "_test.rb", "_test.ts", "_test.js", ".test.ts", ".test.js", ".spec.ts", ".spec.js"} {
		if strings.HasSuffix(base, suf) {
			return true
		}
	}
	return strings.HasPrefix(base, "test_")
}

func isDocPath(slash, base string) bool {
	if strings.HasPrefix(slash, "docs/") || strings.HasPrefix(slash, "doc/") {
		return true
	}
	switch base {
	case "README.md", "README", "CHANGELOG.md", "CONTRIBUTING.md", "LICENSE", "COPYING":
		return true
	}
	return strings.HasSuffix(base, ".md")
}

func isCIPath(slash string) bool {
	return strings.HasPrefix(slash, ".github/") ||
		strings.HasPrefix(slash, ".gitlab-ci") ||
		strings.HasPrefix(slash, ".circleci/")
}

// boringScopes are directory names that name a layout convention, not an
// area of the project. Using one as a conventional-commit scope would read
// as "the src package" rather than what changed. Every key is lowercase, and
// subjectScope folds the directory before looking it up: "SRC" and "src" are
// one directory on a case-insensitive volume, and both name the convention.
var boringScopes = map[string]bool{
	"src": true, "lib": true, "pkg": true, "internal": true, "app": true,
	"cmd": true, "testdata": true, "vendor": true, "scripts": true,
	"workflows": true, "github": true, "circleci": true,
}

func subjectScope(files []string) string {
	var scope string
	for _, f := range files {
		dir := path.Base(path.Dir(filepath.ToSlash(f)))
		if dir == "." || dir == "" || dir == "/" || strings.HasPrefix(dir, ".") ||
			boringScopes[strings.ToLower(dir)] {
			return ""
		}
		dir = commitToken(dir)
		if dir == "" {
			return ""
		}
		if scope == "" {
			scope = dir
			continue
		}
		if scope != dir {
			return ""
		}
	}
	return scope
}

func subjectWhat(files []string, allNew bool) string {
	verb := "update"
	if allNew {
		verb = "add"
	}
	names := displayNames(files)
	switch len(names) {
	case 1:
		return verb + " " + names[0]
	case 2:
		return verb + " " + names[0] + " and " + names[1]
	default:
		return verb + " " + names[0] + " and " + strconv.Itoa(len(names)-1) + " other files"
	}
}

func displayNames(files []string) []string {
	bases := make(map[string]int, len(files))
	out := make([]string, len(files))
	for _, f := range files {
		bases[commitToken(path.Base(filepath.ToSlash(f)))]++
	}
	for i, f := range files {
		slash := filepath.ToSlash(f)
		base := path.Base(slash)
		tok := commitToken(base)
		name := tok
		if bases[tok] > 1 {
			name = commitToken(slash)
		}
		if name == "" {
			name = "file"
		}
		out[i] = name
	}
	return out
}

func commitToken(s string) string {
	// Filenames arrive in whatever form the filesystem handed git (macOS
	// writes NFD); compose so the subject stores the same spelling discovery
	// and signal matching already use, and so a combining mark cannot sit on
	// the 72-rune cut by itself. Sanitize first so dropping a hidden control
	// character leaves the surrounding runes adjacent for composition.
	s = normalize.Sanitize(s)
	s = norm.NFC.String(s)
	return strings.TrimSpace(s)
}

// clipSubject is the one function every subject passes through, whatever its
// source: generated from the changed files, parsed out of agent output, or
// read back out of history during a recovery pass. Sanitizing here rather than
// at each call site means a source added later inherits the guarantee, and it
// is idempotent for the sources that already sanitized upstream.
func clipSubject(s string) string {
	s = norm.NFC.String(normalize.Sanitize(s))
	if utf8.RuneCountInString(s) <= subjectMax {
		return s
	}
	return strings.TrimSpace(normalize.Clip(s, subjectMax))
}
