// Copyright (C) 2026 Marcel W. Wysocki
// SPDX-License-Identifier: AGPL-3.0-or-later

// Reading a finished run back out of its journal: the event stream for
// `gauntlet show <run-id>`, the run id lookup, and the per-review history the
// file-signal suggester weighs past runs by.

package journal

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"time"
)

// Events replays one run's journal, handing each decodable event to visit in
// file order. Used by `gauntlet show <run-id>`. Visiting streams rather than
// collects: a long run's journal is bounded by disk, not by RAM, and every
// consumer prints one line at a time anyway. Lines that do not parse are
// skipped, matching the index reader's tolerance for a killed process.
func Events(runID string, visit func(map[string]any)) error {
	return events(runID, nil, func(line []byte) {
		dec := json.NewDecoder(bytes.NewReader(line))
		dec.UseNumber()
		var m map[string]any
		if err := dec.Decode(&m); err != nil {
			return
		}
		if _, err := dec.Token(); !errors.Is(err, io.EOF) {
			return
		}
		visit(m)
	})
}

// events replays a journal like Events, but when gate is non-nil it is applied
// to each raw line first and only passing lines are visited. A gate is a
// conservative prefilter, not an authority: a line that slips past it is
// handed to visit and decided there. visit must finish with the line before
// returning: the scanner reuses the buffer.
func events(runID string, gate func([]byte) bool, visit func([]byte)) error {
	path, err := findRun(runID)
	if err != nil {
		return err
	}
	return eventsFile(path, gate, visit)
}

func eventsFile(path string, gate func([]byte) bool, visit func([]byte)) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64<<10), 8<<20)
	for sc.Scan() {
		line := sc.Bytes()
		if gate != nil && !gate(line) {
			continue
		}
		visit(line)
	}
	return sc.Err()
}

// ErrNoJournal marks a lookup miss: the run id is not in the tree. Callers
// use it to report a bad command-line argument (usage) rather than a general
// failure.
var ErrNoJournal = errors.New("no journal for run")

// maxRunIDLen bounds a run id: NewRunID produces 23 bytes, and a cap keeps a
// hostile or fat-fingered argument from building absurd paths.
const maxRunIDLen = 128

// validRunID reports whether s may be joined into a journal path. Run ids are
// generated by NewRunID (digits, T, Z, and hex), but the CLI also accepts one
// from the command line, so anything outside the safe charset, and any "..",
// is treated as a lookup miss.
func validRunID(s string) bool {
	if s == "" || len(s) > maxRunIDLen || s == "." {
		return false
	}
	if strings.Contains(s, "..") {
		return false
	}
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z',
			r >= '0' && r <= '9', r == '-', r == '_', r == '.':
		default:
			return false
		}
	}
	return true
}

// findRun locates a run journal by id.
func findRun(runID string) (string, error) {
	if p, ok, err := locateRun(runID); err != nil {
		return "", err
	} else if ok {
		return p, nil
	}
	return "", fmt.Errorf("%w %s under %s", ErrNoJournal, runID,
		filepath.Join(Home(), "runs"))
}

// locateRun returns the path already holding runID's journal, if any.
//
// Generated ids embed the UTC date they were filed under, so that shard is
// tried first: listing every day directory and probing each one would make
// `gauntlet show` and History cost the age of the install, not the one file
// they want. Ids that were not generated that way (tests, a hand-named file)
// still scan, newest shard first, which is also the fallback when the dated
// path is missing (a tree that was rearranged).
//
// The id is validated first: `gauntlet show` hands it over straight from the
// command line, and an unvalidated join would let "../" climb out of the runs
// tree and stat (then read) any *.jsonl the user can reach.
func locateRun(runID string) (string, bool, error) {
	if !validRunID(runID) {
		return "", false, nil
	}
	root := filepath.Join(Home(), "runs")
	if shard := shardFromRunID(runID); shard != "" {
		p := filepath.Join(root, shard, runID+".jsonl")
		if _, err := os.Stat(p); err == nil {
			return p, true, nil
		}
	}
	days, err := os.ReadDir(root)
	if err != nil {
		// A journal tree that does not exist yet means no such run, not a
		// filesystem error: `gauntlet show <id>` before the first run, or on
		// a fresh GAUNTLET_HOME, must read as a miss, not as ENOENT noise.
		if os.IsNotExist(err) {
			return "", false, nil
		}
		return "", false, err
	}
	slices.Reverse(days)
	for _, d := range days {
		if !d.IsDir() {
			continue
		}
		p := filepath.Join(root, d.Name(), runID+".jsonl")
		if _, err := os.Stat(p); err == nil {
			return p, true, nil
		}
	}
	return "", false, nil
}

// shardFromRunID is the date directory NewRunID files a journal under:
// YYYY-MM-DD from the leading YYYYMMDDTHHMMSSZ of a generated id. Anything
// else (a custom name, a truncated stamp, an invalid calendar date or leap day)
// returns "" so locateRun scans.
func shardFromRunID(id string) string {
	if len(id) < 16 || id[8] != 'T' || id[15] != 'Z' {
		return ""
	}
	t, err := time.Parse("20060102T150405Z", id[:16])
	if err != nil {
		return ""
	}
	return t.UTC().Format("2006-01-02")
}

// ReviewHistory is what past runs did with one review in one directory.
type ReviewHistory struct {
	Runs    int // times the review finished there
	Changed int // times it left lines behind
}

// How far back History looks: far enough for a repeat pattern to show, near
// enough that it follows a project that has moved on. Journals are read whole,
// so the number of matching runs is capped as well: the answer is a weighting,
// not an audit, and a machine with a year of runs must not pay for all of them.
const (
	historyRuns    = 30
	historyMatches = 8
)

// reviewEndJSON is the byte form of the one event kind History cares about,
// as the journal encoder writes it: quoted, unescaped ASCII. The gate is a
// prefilter, not a parse, so a stray occurrence elsewhere only costs a decode.
var reviewEndJSON = []byte(`"review_end"`)

// mergeJSON gates for merge events the same way. An isolated review (--jobs)
// publishes its review_end before its own commit exists, so the line counts
// it measured against that commit ride on the merge event instead; without
// this gate, every review that ever ran in worktree mode would look like it
// never changed a line, and the history signal would demote exactly the
// reviews that keep landing work.
var mergeJSON = []byte(`"merge"`)

// pullRequestJSON gates for pull_request events the same way as merge.
// An isolated stacked review (--stacked-prs) publishes its review_end before
// its own commit exists, so the line counts it measured against that commit
// ride on the pull_request event instead.
var pullRequestJSON = []byte(`"pull_request"`)

// historyGate filters out lines that cannot be one of the events History counts.
func historyGate(line []byte) bool {
	return bytes.Contains(line, reviewEndJSON) || bytes.Contains(line, mergeJSON) || bytes.Contains(line, pullRequestJSON)
}

// History reports, per review, how a directory's own past runs went: how often
// each review ran there and how often it actually changed something. It is the
// only signal that improves with use, and it costs one pass over the recent
// journals.
//
// Runs are counted on review_end only when the review finished (status ok, or
// no status on older journals). A skip, timeout, failure, or interrupt is not
// a finished run: counting those as "ran and changed nothing" would demote
// reviews the operator cancelled or that never launched.
// Changed comes from either event that carries the review's measured lines:
// a sequential review's review_end, or the merge event an isolated review's
// work lands through. A merge that did not land (conflict, failure) carries no
// counts and changes nothing, exactly like a review that changed nothing.
//
// Runs that cannot be read are skipped: this is a convenience log, and a
// suggestion is not worth failing over.
func History(dir string) (map[string]ReviewHistory, error) {
	runs, err := Recent(historyRuns)
	if err != nil {
		return nil, err
	}
	out := map[string]ReviewHistory{}
	matched := 0
	for _, run := range runs {
		if !slices.Contains(run.Dirs, dir) {
			continue
		}
		if matched++; matched > historyMatches {
			break
		}
		visit := func(line []byte) {
			var e historyEvent
			if err := json.Unmarshal(line, &e); err != nil {
				return
			}
			if e.Dir != dir || e.Review == "" {
				return
			}
			ins, del := e.Ins, e.Del
			switch e.Ev {
			case "review_end":
				if e.Status != "" && e.Status != "ok" {
					return
				}
				h := out[e.Review]
				h.Runs++
				if ins+del > 0 {
					h.Changed++
				}
				out[e.Review] = h
			case "merge", "pull_request":
				// The run itself is already counted by this review's
				// review_end; the merge only ever adds whether it landed
				// measured work. The loop-step merge into --merge-into
				// carries no counts and names a branch, not a review, so it
				// falls out on both.
				if e.Status != "ok" {
					return
				}
				if ins+del > 0 {
					h := out[e.Review]
					if h.Changed < h.Runs {
						h.Changed++
						out[e.Review] = h
					}
				}
			}
		}
		if run.Path != "" {
			if err := eventsFile(run.Path, historyGate, visit); err == nil {
				continue
			}
		}
		_ = events(run.RunID, historyGate, visit)
	}
	return out, nil
}
